# Generated by Django 5.1.2 on 2024-10-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agricultor',
            managers=[
            ],
        ),
    ]
