# Generated by Django 5.1.2 on 2024-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planta_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantacultivada',
            name='data_plantio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantacultivada',
            name='percentual_perda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plantacultivada',
            name='quantidade_plantada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
